#whitelist:
#  - markdown_link_replacer
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-paginate
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
#  - markdown_link_replacer
exclude:
  - jekyll_tmp
relative_links:
  enabled: true
  collections: true
markdown: CommonMarkGhPages # GFM
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
#highlighter: rouge
#markdown: redcarpet   #rdiscount, kramdown, redcarpet, CommonMarkGhPages, CommonMark
#kramdown:
#  input: GFM # 启用 GitHub Flavored Markdown
#  syntax_highlighter: rouge # 使用 Rouge 作为代码高亮器
#  # 其他配置选项，根据需要调整
#markdown: redcarpet
#redcarpet:
#  extensions: ["autolink", "no_intra_emphasis", "tables", "strikethrough"]

permalink: pretty
readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: false
title: shlu's tool
logo: favicon.ico
tagline: 常用工具使用和填坑
description: 一名Android&iOS逆向分析Boy
#safe: false
author:
  name: shlu
  url: https://t.me/shluer
social:
  name: shlu
  links:
    - https://github.com/jitcor

# GitHub page default theme :jekyll-theme-primer
# docs: https://www.rubydoc.info/gems/jekyll-theme-primer/0.6.0
# source: https://github.com/pages-themes/primer
# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

url: "https://jitcor.github.io"

show_warnings: true
